---
- name: Installation of Packages and Preparing the System
  hosts: quay

  tasks:

## Install the container tools packages for Podman
    - name: Install Podman Packages
      dnf:
        name: '@container-tools:rhel8'
        state: present

## Prepare firewall for Quay
    - name: Enable Firewall Ports
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - 8443/tcp
        - 8080/tcp
        - 443/tcp
